# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170102_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wide_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'product_pics_wide'),
        ),
    ]
